#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-mysql
version:      3.0002
version_from: lib/DBD/mysql.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    DBI:                           1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
